name: junitreport
version: 2.0.4
description: Generate JUnit XML reports from dart test runs. Transforms the output of dart or flutter tests to
  JUnit style XML

homepage: https://github.com/TOPdesk/dart-junitreport

dependencies:
  args: ^2.4.2
  intl: ^0.18.1
  testreport: ^2.0.1
  xml: ^6.4.2

dev_dependencies:
  test: any
  lints: 2.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  tojunit: